### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by ffont** [AudioCommons/ac-mediator#13]
Should we already start including API versioning in api url endpoints? `/api/v1/...`?

**Comment by alastair** [comment]
Is the mediator domain (m.ac.org) only going to run an API, or other interfaces as well (in which case, do we need `/api`?

Versioning can be annoying. Some people recommend using subdirectories, some people recommend using headers: http://stackoverflow.com/a/6750376

I know you use `v1` in freesound, but I've also used just a number.

In specific answer to your question, yes, I think we should including versioning from the beginning. I don't know which system we should use, though.

**Comment by ffont** [comment]
The mediator will not only return api calls but also other interfaces, that's why we use `/api/`.

I think `v#` is better to just a number `#` as in my opinion is more self-explanatory.
I don't like the idea of using a header as the information is a lot less explicit, also using sub-directories can be confusing as is clearly separating other mediator's interfaces from API.
Many well-known APIs add version in the url so I think this is a good way to go.
I'll add `/api/v1/` for now and see how it works.
